### ISSUE TITLE
Broken after fd0f46977c4b1432a90c52c663081ce63c8adcf5

### ISSUE THREAD

**Issue by ODAKAB** [darkbot-reloaded/DarkBot#12]
It compiles but doesn't run(crashes?) after:
https://github.com/darkbot-reloaded/DarkBot/commit/fd0f46977c4b1432a90c52c663081ce63c8adcf5

JDK: Java 8 261
JRE: Java 8 241

**Comment by Pablete1234** [comment]
Fixed in 65f1741
