### ISSUE TITLE
Error during instalation

### ISSUE THREAD

**Issue by LuisD20** [darkbot-reloaded/DarkBot#193]
![Screenshot_1](https://user-images.githubusercontent.com/70770072/205408225-94278a7e-c6da-4967-8c74-093758058ad9.png)

i already install c++ from microsoft and follow the installation guide from darkbo guide but still get this error

**Comment by TeYroXOfficial** [comment]
This error means it already installed C++. 
It's just a runtime, it won't install bot itself. You need to download it from our discord server.

**Comment by LuisD20** [comment]
that is true the bot work perfect
