### ISSUE TITLE
good morning I have a problem with the bot practically when an enemy uses the DRAW FIRE skill the bot disconnects and does not re-login by itself if I don't press play on the bot

### ISSUE THREAD

**Issue by scelly97** [darkbot-reloaded/DarkBot#220]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**

**Logs**

Attach your logs, they can be found in the logs folder.

**Enviroment**

 - OS: [e.g. win7, win10, win11, linux]
 - Bot Version: [e.g. 1.117]
 - Browser API & version: [e.g. KekkaPlayer v21]
 - Plugins installed: [e.g. Default Plugin v2.0.0, OtherPlugin v1.0.0]

**Additional context**

**Checks**

 - [ ] I have checked i'm running the latest version released
 - [ ] I have reproduced the issue without any plugins except the minimum required
 - [ ] I have attached screenshots and/or videos to show the problem
 - [ ] I have attached the logs of the issue
 - [ ] I have confirmed with someone else they can reproduce the issue

**Comment by scelly97** [comment]
![Uploading 96C1DC07-94DB-4129-992F-088F9752A199.jpeg…]()

**Comment by Pablete1234** [comment]
The template exists for you to fill it in. Reports without filling in the template will not be attended.
