### ISSUE TITLE
Bug darkbot palladium 

### ISSUE THREAD

**Issue by scelly97** [darkbot-reloaded/DarkBot#221]
![BA69BE21-2F69-437E-BF91-E8D9EDBEE20E](https://user-images.githubusercontent.com/122008596/211004287-156bd5f6-f9d8-407e-afe6-2705e7ae7656.jpeg)

**Comment by scelly97** [comment]
can you do something to enable DRAW FIRE because otherwise it always logs out and never logs back in unless I click play

**Comment by Pablete1234** [comment]
Follow the template
