### ISSUE TITLE
Offensive Ability Key Does Not Work

### ISSUE THREAD

**Issue by LUCYCAT22** [darkbot-reloaded/DarkBot#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

Offensive Ability Key Does Not Work

### Expected Behavior

Using offensive ability key

### Steps To Reproduce

You can understand the issue by watching the video.

### Screenshots, Video, or other media

https://user-images.githubusercontent.com/122293338/211350354-04669052-4475-46c2-aac6-c96d7af61f8e.mp4

### Bot Version

DarkBot v1.117

### Installed Plugins & versions

Default Plugin v2.0.0

### Browser API & version

KekkaPlayer v24

### Operating System

Win10 Pro

### Anything else?

I reported this issue for beta 112 version and the issue persists in the latest version

**Comment by Arcia** [comment]
Hello,

I have the same issue, but with a Venom ship. Bot never use the configured ability in the panel.

**Comment by Pablete1234** [comment]
Fixed upstream, will be available in the next release
