### ISSUE TITLE
When I open the bot it keeps loading endlessly

### ISSUE THREAD

**Issue by Joaquin4745** [darkbot-reloaded/DarkBot#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

When I try to start the bot everything is fine until it reaches the loading screen, which is when it loads less than half and automatically restarts itself

### Expected Behavior

Let the bot enter the game

### Steps To Reproduce

1.- inicie el bot como normalmente lo uso
2.- trato de entrar al juego y no deja de reiniciarse

### Screenshots, Video, or other media

![WhatsApp Image 2023-01-22 at 1 09 08 AM](https://user-images.githubusercontent.com/123289176/213904842-dbaa4963-a682-4184-8094-f5ada659ff0f.jpeg)

### Logs

nothing here

### Bot Version

Bot version 1.117

### Installed Plugins & versions

Default plugin v2.0.1 (deleted all other plugins, issue persists)

### Browser API & version

Browser API & version: KekkaPlayer v24

### Operating System

OS:win10

### Anything else?

When trying to use the bot it seemed strange to me that the game did not load because a day before I had used the bot and when I entered normally, if I opened it and everything was fine, I looked for various solutions that some friends gave me and among many things that I tried to do I tried to check if it was the same version as the one with the problem and for a while apparently that was because I tried v1.112 and it worked for me but I couldn't use any of the updated plugins some time later that version gave me problems but it should work correctly

**Comment by diiamxnd** [comment]
i have the same problem on one vps, after 48 refresh finnaly can open the game, im using a fresh bot folder
[BotLog](https://github.com/darkbot-reloaded/DarkBot/files/10505906/2023-01-25_17-28-13_828.log)
[Video](https://youtu.be/TEiaTj25GhU)

**Comment by Pablete1234** [comment]
Fixed in 1.118 release
