### ISSUE TITLE
Bot freezes entirely after 58 hours  , issue resolved after manually fully  closing the bot entirely .

### ISSUE THREAD

**Issue by Kirewer** [darkbot-reloaded/DarkBot#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

Bot got fully frozen and ignored basically everything from 2 am till i checked it today at 10 am . Bot window as you can see fully lagging no matter is it on or off ( i keep it at 30 fps thats why you can see the bot going from 60 fps when off to 30 when on ! ) 

### Expected Behavior

To not be frozen or lagging after x amount of time , causing losing decent amount of time in doing basically nothing . 

### Steps To Reproduce

1.Start the bot
2.Wait 58 hours while collecting clashes in random maps with some stops and abg (  i doubt its the abg part but thats what i did)
3. keep collecting the solar clash
4. ??
5. voila issue 

### Screenshots, Video, or other media

https://user-images.githubusercontent.com/123942022/215447266-4296d109-082a-4567-bbe5-afd02dbd28d9.mp4

https://streamable.com/8s1ks1 - in case the video fails to get uploaded by any reason 

### Logs

[2023-01-27_23-18-44_136.log](https://github.com/darkbot-reloaded/DarkBot/files/10534654/2023-01-27_23-18-44_136.log)

### Bot Version

v.1.117

### Installed Plugins & versions

All plugins are up to date !
Default plugin v2
Launch v1.0.5
!lean plugin v1.3.6
Pika plugin v1.6.86
Donor plugin v2.0.3
Kekka Reloaded v1.6.6 b23
Penguin v3.0.1 

### Browser API & version

KekkaPlayer v24

### Operating System

win 10 21h2 (os  build 19044.2486)

**Comment by Pablete1234** [comment]
As the issue report form says, remove all plugins and reproduce the issue before reporting.
