### ISSUE TITLE
PikaPika Plug in not working 

### ISSUE THREAD

**Issue by JourneyMTL** [darkbot-reloaded/DarkBot#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

![ce8c214467b14c560ef2e43abae4eb46](https://user-images.githubusercontent.com/125417216/218894291-d5044ec5-195b-4fdb-8517-31e54e28789a.png)

### Expected Behavior

when having the PikaPika plugin in the folder it doesnt not load the bot and when its removed from the folder it loads up normally 

### Steps To Reproduce

1. load bot normally with the plugin inside the plugin folder with the latest version 118
2. will not load the windows for bot 
3. remove plug in from folder (Pika)
4. load bot and it works perfect but you will not have dispatch 

### Screenshots, Video, or other media

all submitted

### Logs

[2023-02-13_17-50-40_181.log](https://github.com/darkbot-reloaded/DarkBot/files/10738002/2023-02-13_17-50-40_181.log)
[2023-02-13_22-24-46_540.log](https://github.com/darkbot-reloaded/DarkBot/files/10738003/2023-02-13_22-24-46_540.log)
[2023-02-13_22-25-43_973.log](https://github.com/darkbot-reloaded/DarkBot/files/10738004/2023-02-13_22-25-43_973.log)

### Bot Version

v1.118

### Installed Plugins & versions

default
donor
kekka
lean
osiris

### Browser API & version

Kekka 1.6.6

### Operating System

win 11

### Anything else?

n/a

**Comment by Pablete1234** [comment]
This is not the place to submit plugin issues, if the bot works correctly without the plugin i consider this solved
