### ISSUE TITLE
BUG in CustomEvents(DmPlugin)

### ISSUE THREAD

**Issue by NioCZ** [darkbot-reloaded/DarkBot#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

There is problem with brackets interference when using string() command and  brackets inside-> like string(( UberKristallon)) ...

### Steps To Reproduce

Open customevents
In conditions input String()
try to put string with brackets in it ...()

### Screenshots, Video, or other media

![image](https://user-images.githubusercontent.com/126159133/220883034-4afa52cc-1bda-4f2c-949a-78daac514b45.png)

### Logs

My log is too big :D over 176MB :D sorry 

### Bot Version

1.118

### Installed Plugins & versions

DmPlugin v1.7.23

**Comment by Pablete1234** [comment]
Escape the closing parenthrsis with \

**Comment by NioCZ** [comment]
thanks it works! can you make a note in customevents to educate others
