### ISSUE TITLE
In-game captcha box capture does not work as DO servers have moved spacemap/templates/EUR/flashres.xml somewhere else

### ISSUE THREAD

**Issue by KlokanFan** [darkbot-reloaded/DarkBot#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

Bot tries to retrieve language resource file from "https://darkorbit-22.bpsecure.com/spacemap/templates/EUR/flashres.xml", file was moved to (i assume) "https://darkorbit-22.bpsecure.com/spacemap/templates/en/flashres.xml". For Czech I have found "https://darkorbit-22.bpsecure.com/spacemap/templates/cs/flashres.xml" works.

I can confirm I am unable to retrieve the resource file with my default in-game language (Czech) and whenever I force language to be English.

A French person in Discord claimed French/French does not work either, I have not tested that one. Multiple people in Discord have claimed their in-game captcha box picker does not work as well.

It is possible bot is only confused whenever it has to pick up all boxes as all scenarios I was stuck in I remember I was asked to pick all boxes of a certain color. 

### Expected Behavior

DarkBot is unable to resolve the in-game captcha box picker thing, waits to receive a log message that has already come through. 

### Steps To Reproduce

1. Set DarkBot to English.
2. Allow DarkBot to force set the In-game language to English.
3. Eventually, the bot will be asked to do an in-game box pickup captcha, in which the box will be stuck waiting for a log message.

### Screenshots, Video, or other media

Logs should be sufficient I assume. Contact me on Discord (KlokanFan#0081) in case you really need to see it.

### Logs

[2023-03-01_17-31-21_919.log](https://github.com/darkbot-reloaded/DarkBot/files/10864298/2023-03-01_17-31-21_919.log)

### Bot Version

1.118

### Installed Plugins & versions

Default Plugin v2.0.0 (by Popcorn)

### Browser API & version

KekkaPlayer v24

### Operating System

Win10

### Anything else?

Thank you for updating and developing DarkBot, very cool of you.

**Comment by Pablete1234** [comment]
Fixed in #259
