### ISSUE TITLE
Nimesis plugin bugs

### ISSUE THREAD

**Issue by bsthethor** [darkbot-reloaded/DarkBot#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

Bot is succesfully starting at the begining of the hour but not jump to nemesis correctly. Player must do it by him/herself.
The second thing about nimesis plugin is end of the gate. Bot not jump to end of the gate. Please fix this problem asap. Because event is started. So we need to use a running nimessis plugin.

### Steps To Reproduce

1-)Select nimesis plugin from plugins.
2-) wait to gate open.
3-) then u saw that the bot is not jump in to nemesis.

### Screenshots, Video, or other media

there is no media from my side.

### Logs

don't have one

### Bot Version

1.119

### Installed Plugins & versions

Donor v2.0.0

**Comment by Pablete1234** [comment]
Fixed in #263
