### ISSUE TITLE
Captcha bug

### ISSUE THREAD

**Issue by Hyperrandomm** [darkbot-reloaded/DarkBot#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

The bot randomly doesn't do the captcha. Does the captcha after bot is closed and re-opened.

### Expected Behavior

Bot should always solve captcha.

### Steps To Reproduce

Sadly, I don't know. There doesn't seem to be anything specific that triggers it. Longest run before the bug appeared was 17 hours. Sometimes it occurs after 2-3 hours sometimes after 10+ hours.

### Screenshots, Video, or other media

https://user-images.githubusercontent.com/127903311/226421954-45c928e7-f725-4f08-bdd9-b7e35d7e529f.mp4

### Logs

[2023-03-20_16-24-08_619.log](https://github.com/darkbot-reloaded/DarkBot/files/11021313/2023-03-20_16-24-08_619.log)

### Bot Version

1.120

### Installed Plugins & versions

Default Plugin v2.0.0

### Browser API & version

KekkaPlayer v24

### Operating System

Win10

### Anything else?

Since the bot functions after it is restarted a quick temporary fix could be to make a simple program that automatically closes and re-opens the bot and resumes the previous session.

If you have any questions I'll answer them as soon as I can. My discord: Hyperrandom#1859

**Comment by fabio1999ita** [comment]
try to force lang to english in game from bot

**Comment by Hyperrandomm** [comment]
> try to force lang to english in game from bot

Will try. It happened with forced english too, but it might reduce the chance.

**Comment by Hyperrandomm** [comment]
https://user-images.githubusercontent.com/127903311/226454246-e0c405e1-de02-4ed3-af00-7c0e492c7618.mp4

**Comment by Hyperrandomm** [comment]
> 

Forced english, only Default plugin active.

**Comment by Pablete1234** [comment]
Could you show what happens if you don't pause the bot and just let it keep running. It should trigger a restart after a couple minutes of being stuck. Does that solve it?

**Comment by Hyperrandomm** [comment]
> Could you show what happens if you don't pause the bot and just let it keep running. It should trigger a restart after a couple minutes of being stuck. Does that solve it?

No it doesn't. I came home many times to the bot just being stuck for hours, since my uri/h was way down to like 10k (even in worst case with lots of players it shouldn't go below 40k/h). Also waited for multiple restarts while watching the bot and nothing happened just stayed stuck and sometimes instead of "collecting x boxes" said "waiting for log".

**Comment by Hyperrandomm** [comment]
> Could you show what happens if you don't pause the bot and just let it keep running. It should trigger a restart after a couple minutes of being stuck. Does that solve it?

The bug didn't happen in a while, but when it does I'll try to get a video of the bot refreshing. But as I have said in my previous comment, nothing changes. I came home to the bot having refreshed more than 1000 times and was still stuck in captcha.

**Comment by lvantunes** [comment]
I've seen this issue recently as well. If I see it again, I'll record it and post it here.

**Comment by Pablete1234** [comment]
Closing as stale, doesn't seem like anyone is able to reproduce it
