### ISSUE TITLE
Pet locator confuses UberStreuner with UberStreuneR

### ISSUE THREAD

**Issue by lvantunes** [darkbot-reloaded/DarkBot#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

I set up the bot to ONLY kill ( UberStreuner ) on 4-5 map with "Enemy Locator" on Pet settings and in the "NPC killer" tab the ( UberStreuner ) NPC's "Extra" I chose "Pet Locator" again. In game, instead of picking ( UberStreuner ) the bot picked ( UberStreuneR )

### Steps To Reproduce

1. Choose 4-5 map;
2. In "NPC Killer" tab choose ( UberStreuner ) and in extras pick "PET Locator"
3. In "Pet" tab choose "Enemy Locator"

### Screenshots, Video, or other media

![Captura de ecrã 2023-03-05 233514](https://user-images.githubusercontent.com/25854375/229383753-81388c55-5ac5-4fdb-98d9-774bfc662a50.png)

![Captura de ecrã 2023-04-03 000150](https://user-images.githubusercontent.com/25854375/229383754-9f81e8f8-f1e7-48ce-835b-3a62fc752163.png)

![Captura de ecrã 2023-04-03 000218](https://user-images.githubusercontent.com/25854375/229383822-5ece6d10-f49c-442c-a869-3c887e8675c2.png)

### Logs

[2023-04-02_23-33-08_082.log](https://github.com/darkbot-reloaded/DarkBot/files/11133549/2023-04-02_23-33-08_082.log)

### Bot Version

v1.120

### Installed Plugins & versions

Default plugin v2.0.0
Kekka Reloaded v1.6.6 b23
Donor Plugin v2.1.1

### Browser API & version

KekkaPlayer v24

### Operating System

Windows 11

**Comment by Pablete1234** [comment]
Fixed in #319
