### ISSUE TITLE
FPS limit not working while 'Pause after refresh'

### ISSUE THREAD

**Issue by m9w** [darkbot-reloaded/DarkBot#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

> v1.13.17 beta 112:
> - FPS limiter only works when bot is running

This change impact on "Pause after refresh". FPS not limiting therefor large CPU usage in pause time.

Possible fix: stop KekkaPlayer while bot is paused by this feature.

### Expected Behavior

Bot not use more resources in pause time than in running time

### Steps To Reproduce

1. Set pause time > 0
2. Set limit FPS
3. Run bot
4. Check FPS and CPU usages
5. Wait pause
6. Compare FPS and CPU usage

### Screenshots, Video, or other media

![image](https://github.com/darkbot-reloaded/DarkBot/assets/52008918/a5f92d80-a9a9-4b0f-9063-44818bc484bb)

### Logs

Not required

### Bot Version

v1.121 b-1 a4

### Installed Plugins & versions

Not required

### Browser API & version

KekkaPplayer v24

### Operating System

Win10 22H2 19045.2846

**Comment by Pablete1234** [comment]
Fixed in 5fe953b4, now fps limit will always apply regardless of if paused or running
