### ISSUE TITLE
Problem on Darkbot 1.122 .jar

### ISSUE THREAD

**Issue by 13erkcan** [darkbot-reloaded/DarkBot#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

There are serious issues with Darkbot 1.122. I was using version 121 until yesterday. Yesterday, I updated it to 1.122. Now, the bot wastes a lot of time chasing and approaching NPCs before attacking them. Isn't there any command for this? Like an instant challenge or an immediate first attack? It takes around 5 hours to chase down X-7 Kristallons or Kristalls, regardless of my ship's speed. Whether I'm fast or slow, it's the same. It constantly approaches while maintaining a certain distance. Initially, it should directly approach and hit the creature to draw its attention and then cut within the recommended radius. Otherwise, there is a significant loss of time.

Despite increasing my ship's damage in the past 2 days, the hourly uranium value has decreased. I used to collect around 8.5k per hour, but now it has dropped to 6.7k after updating the bot. It responds much slower to everything. Version 1.121 was much better. I don't know why this is happening. All my settings are correct. Is there anyone who can help?

### Expected Behavior

I expected it as working better, and faster. Nevertheless, It is not.

### Steps To Reproduce

  ...

### Screenshots, Video, or other media

![Screenshot 2023-07-05 044422](https://github.com/darkbot-reloaded/DarkBot/assets/34860744/e4f3f9a7-255e-48c1-a8dc-df7a652abf55)
![Screenshot 2023-07-05 044501](https://github.com/darkbot-reloaded/DarkBot/assets/34860744/77d4a827-f8a0-4268-a45b-a9cb13762043)

### Logs

These are the last 2 log files

[2023-07-04_17-09-52_893.log](https://github.com/darkbot-reloaded/DarkBot/files/11951790/2023-07-04_17-09-52_893.log)
[2023-07-04_14-57-33_451.log](https://github.com/darkbot-reloaded/DarkBot/files/11951793/2023-07-04_14-57-33_451.log)

### Bot Version

Darkbot 1.122

### Installed Plugins & versions

Default Plugin v2.0.0 by Popcorn
Donor Plugin v2.1.1 by Popcorn

### Browser API & version

KekkaPlayer v24

### Operating System

Win11

**Comment by Pablete1234** [comment]
The difference between 121 and 122 is purely a map name being added. In no possible way is what you're describing possible from that change.

The most likely scenario is that your ping is worse, the server you bot on runs slower today, your PC is overloaded and so the bot ticks slower, or something else unrelated to the bot version itself.
