### ISSUE TITLE
Kekka plugin, galaxy module, 

### ISSUE THREAD

**Issue by RLugan** [darkbot-reloaded/DarkBot#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

The minimum number of lives to jump in the gate is set to 3, bot did the gate till it died and lost all lives.

### Expected Behavior

Bot stops going in the gate at 3(or 2) lives.

### Steps To Reproduce

1. Latest bot version 1.126
2. minimum lives 4, (lost beta and gamma gate), redoing beta and noticed I had 1 life, so bought another one thus 2 lives in the image below.

### Screenshots, Video, or other media

![image](https://github.com/darkbot-reloaded/DarkBot/assets/77074990/d69a021b-a145-4a0b-b195-4c76e6722c96)

### Logs

[2023-07-29_01-52-07_307.log](https://github.com/darkbot-reloaded/DarkBot/files/12207822/2023-07-29_01-52-07_307.log)

### Bot Version

v1.126

### Installed Plugins & versions

Kekka plugin

### Operating System

Win 11

**Comment by Pablete1234** [comment]
This is not a bot issue. It's a kekka plugin issue that stems from gate helper not working due to it relying in old darkbot internals for old gg spinner instead of the spinner API. Please report it to the plugin author.
