### ISSUE TITLE
rapor

### ISSUE THREAD

**Issue by uygarguler** [darkbot-reloaded/DarkBot#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

s.a.   sorun 1  gg haritasında bölüm bitince  atlamadan kalıyor ve haritadan atıyor sonra galaksi kapıları  kayboluyor  yenilemek gerekiyor  2 uçuş düzenleri  değişkenlik sergiliyor ve  botu durdurup elle seçmeye çalışsanda işaretlenmiyor 3 gop kapısında yeşıl halkaya  gitmiyor

### Steps To Reproduce

s.a.   sorun 1  gg haritasında bölüm bitince  atlamadan kalıyor ve haritadan atıyor sonra galaksi kapıları  kayboluyor  yenilemek gerekiyor  2 uçuş düzenleri  değişkenlik sergiliyor ve  botu durdurup elle seçmeye çalışsanda işaretlenmiyor 3 gop kapısında yeşıl halkaya  gitmiyor

### Screenshots, Video, or other media

![kapı](https://github.com/darkbot-reloaded/DarkBot/assets/140953001/1b4f8906-0910-49d3-8edd-b5aa58032fea)

### Logs

[2023-07-30_12-01-03_416.log](https://github.com/darkbot-reloaded/DarkBot/files/12209135/2023-07-30_12-01-03_416.log)
[2023-07-30_12-02-43_675.log](https://github.com/darkbot-reloaded/DarkBot/files/12209136/2023-07-30_12-02-43_675.log)
[2023-07-30_13-16-03_877.log](https://github.com/darkbot-reloaded/DarkBot/files/12209137/2023-07-30_13-16-03_877.log)

### Bot Version

1,126

### Installed Plugins & versions

??

### Browser API & version

KekkaPlayer 24

### Operating System

win 10

**Comment by Pablete1234** [comment]
English only.
