### ISSUE TITLE
Discord Presence Puzzle Pirates: Dark Seas

### ISSUE THREAD

**Issue by LordBucea** [darkbot-reloaded/DarkBot#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

When you open the bot, you will have the Discord presence detect a steam game. Puzzle Pirates: Dark Seas
Puzzle Pirates: Dark Seas
PROGRAM FILES/JAVA/JDK-II 012/BlN/JAVAW EXE this is the path that is being detected

### Expected Behavior

The bot shouldn't be detected as a game in Discord. 

### Steps To Reproduce

1. Windows 11, Version 10.0.22621 Build 22621
2. Launch DarkBot 1.127
3. Check presence in Discord

### Screenshots, Video, or other media

![image](https://github.com/darkbot-reloaded/DarkBot/assets/143594790/53b91840-c7cb-4daa-9207-ecec69e38995)
![image](https://github.com/darkbot-reloaded/DarkBot/assets/143594790/0c9f472c-59b7-41c4-967a-60012b7d7bcc)

### Logs

[2023-08-29_21-27-23_356.log](https://github.com/darkbot-reloaded/DarkBot/files/12473405/2023-08-29_21-27-23_356.log)
[2023-08-30_08-56-01_391.log](https://github.com/darkbot-reloaded/DarkBot/files/12473406/2023-08-30_08-56-01_391.log)
[2023-08-30_09-38-26_861.log](https://github.com/darkbot-reloaded/DarkBot/files/12473407/2023-08-30_09-38-26_861.log)
[2023-08-30_11-21-01_518.log](https://github.com/darkbot-reloaded/DarkBot/files/12473408/2023-08-30_11-21-01_518.log)

### Bot Version

1.127

### Installed Plugins & versions

no plugins in this test

### Browser API & version

Kekka Player 24

### Operating System

Windows 11 Pro Version	10.0.22621 Build 22621

**Comment by Pablete1234** [comment]
Report it to discord, this isnt darkbot's fault
