### ISSUE TITLE
There is something wrong with select module

### ISSUE THREAD

**Issue by ZAG0R** [darkbot-reloaded/DarkBot#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

I dont know what i do or dont. But there are 2 bot in the same machine. It's working without problem but there is problem with select module text. U can see from gif.

### Steps To Reproduce

.

### Screenshots, Video, or other media

![Animation](https://github.com/darkbot-reloaded/DarkBot/assets/10741438/257bc0ce-601d-4657-90b9-81e074bb3e07)

### Logs

[2023-10-23_10-26-24_018.log](https://github.com/darkbot-reloaded/DarkBot/files/13068981/2023-10-23_10-26-24_018.log)

### Bot Version

1.128.3

### Installed Plugins & versions

![Adsız](https://github.com/darkbot-reloaded/DarkBot/assets/10741438/f075c7a9-35b3-4f65-b24d-082ddb07dd92)

There are installed plugins but i just using Lean, Osiris(Auto-Buy), Pika(Dispatch, Logout when admin detected), Default Plugin and DM Plugin (Weekly Sch. , Others, Custom Events.)

### Operating System

Windows Server 2016

### Anything else?

.

**Comment by ZAG0R** [comment]
Umm i think problem related with DM plugin cause i have picked Reload if memory exceeded from 2000. And i just saw my memory over than 2000 so i think its the problem. Maybe DM plugin is bugged.

**Comment by Pablete1234** [comment]
If you're able to reproduce the issue without having 10 plugins, installed, please reopen the issue
