### ISSUE TITLE
command center problem on game screen

### ISSUE THREAD

**Issue by fkanberi** [darkbot-reloaded/DarkBot#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

Hello, the command center no longer closes after opening the bot

### Expected Behavior

The behavior I expect is automatic closing of that tab.

### Steps To Reproduce

1. When I open the bot, the tabs that should be closed do not close
2. no other problems

### Screenshots, Video, or other media

sorry I don't have it

### Logs

[2023-12-25_21-17-08_300.log](https://github.com/darkbot-reloaded/DarkBot/files/13767018/2023-12-25_21-17-08_300.log)
[2023-12-25_21-21-43_127.log](https://github.com/darkbot-reloaded/DarkBot/files/13767019/2023-12-25_21-21-43_127.log)

### Bot Version

v 1.129

### Installed Plugins & versions

![image](https://github.com/darkbot-reloaded/DarkBot/assets/39139444/ab011287-5563-43eb-81ed-9bb93e4ccf9d)

### Browser API & version

kekka player v25 {119]

### Operating System

windows server 2019

**Comment by Punikekk** [comment]
Bot will close them if u click `PLAY` button
