### ISSUE TITLE
Bot spinning while gate is built

### ISSUE THREAD

**Issue by Barka108** [darkbot-reloaded/DarkBot#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

spinning gates while gate is already built

### Expected Behavior

Stop spinning

### Steps To Reproduce

Unknown

### Screenshots, Video, or other media

https://gyazo.com/bc084bc9addf7386237ac97cb83e21cc

### Logs

NA

### Bot Version

1.129

### Installed Plugins & versions

all

### Browser API & version

NA

### Operating System

Win11

### Anything else?

NA

**Comment by Pablete1234** [comment]
This was already tweaked/resolved in updates to the spinning plugin
