### ISSUE TITLE
Mimesis bug - doesn't jump out

### ISSUE THREAD

**Issue by PatrikGazdik** [darkbot-reloaded/DarkBot#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

The bot just stays inside mimesis gate. I got everything set and it still doesnt want to jump out, idk what else can i do. Im not the only one, many other people experience this problem

### Expected Behavior

Bot jumps out of gate after EM dies 

### Steps To Reproduce

Make the bot jump out of gate. I tried what i could, but didnt manage to work it out

### Screenshots, Video, or other media

![image](https://github.com/darkbot-reloaded/DarkBot/assets/100072890/e27a11b4-e9ab-4b75-95da-022ba0ab1a95)
![image](https://github.com/darkbot-reloaded/DarkBot/assets/100072890/b0935edd-5e95-4c64-bac3-f2da9907e6b0)
![image](https://github.com/darkbot-reloaded/DarkBot/assets/100072890/f1089ad5-abf9-48d7-a428-86a8e6a87185)
![image](https://github.com/darkbot-reloaded/DarkBot/assets/100072890/e108497c-4f3f-4baa-9b06-4871fddd052f)
![image](https://github.com/darkbot-reloaded/DarkBot/assets/100072890/6fa1f313-d960-4430-98cf-cdae3b72f369)

### Logs

[2024-03-14_10-59-06_355.log](https://github.com/darkbot-reloaded/DarkBot/files/14600980/2024-03-14_10-59-06_355.log)
[deaths_2024-03-14_10-59-06_355.log](https://github.com/darkbot-reloaded/DarkBot/files/14600981/deaths_2024-03-14_10-59-06_355.log)
[2024-03-14_10-59-07_KekkaPlayer.log](https://github.com/darkbot-reloaded/DarkBot/files/14600983/2024-03-14_10-59-07_KekkaPlayer.log)

### Bot Version

1.129

### Installed Plugins & versions

default v2.2.0
donor v2.2.3
!leanplugin v1.6.5 b1

### Browser API & version

Kekkaplayer v26

### Operating System

win11

**Comment by Pablete1234** [comment]
Fixed in abf25011d216ef30b71d2a58ff0dbc7eac46c67d
