### ISSUE TITLE
credit per hour bugged

### ISSUE THREAD

**Issue by Saiitama** [darkbot-reloaded/DarkBot#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

When spending credit in the auction, and losing the auction, we get the credits back, bot those gets accounted in the cre/h as if the bot farmed it.

### Expected Behavior

getting credits back from lost auction, should not count towards cre/h

### Steps To Reproduce

already explained above

### Screenshots, Video, or other media

.

### Logs

.

### Bot Version

.

### Installed Plugins & versions

.

**Comment by Pablete1234** [comment]
This is not a bug, working as intended. The bot has no way to differentiate the source of credits, it just tracks earned credits. It already exposes (via API) ways of getting not just earned but also earned, spent, or diff (earned - spent) which plugins can use to show different graphs or data, but there's no plan to try and track/separate auction credit usage, and if there was, it'd be as a feature request not a bugfix.

**Comment by Saiitama** [comment]
i see, but can't it read in the homepage from the uridium page in the balance section that i got refunded back credits from auction and then count those out?
