### ISSUE TITLE
Enemy Locator with MiniCore > PetLink

### ISSUE THREAD

**Issue by mateuzplays** [darkbot-reloaded/DarkBot#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

So I am using MiniCore > PetLink but im also using enemy locator, what happens is the pet gets stuck with the repair module, getting no repair and dont change back to enemy locator.

### Expected Behavior

What i expect to happens is to repair the pet everytime its needed and then switch back to the enemy locator module.

### Steps To Reproduce

Somewhere, just use pet locator in any npc on the map, active MiniCore > PetLink > HPLink & repair pet health. 
Then let the pet get damaged a few times, eventually will get stuck in the repair module without repairing the pet and without switching back to the enemy locator.

### Screenshots, Video, or other media

.

### Logs

[2024-06-25_00-18-25_601.log](https://github.com/user-attachments/files/15962920/2024-06-25_00-18-25_601.log)
[2024-06-25_00-18-30_KekkaPlayer.log](https://github.com/user-attachments/files/15962921/2024-06-25_00-18-30_KekkaPlayer.log)

### Bot Version

1.131.1

### Installed Plugins & versions

Default plugin 2.0.0
DmPlugin 2.2.10
LeanPlugin 1.6.6
MiniCore 1.5.6
Optimal 1.0.6
Osiris 1.6.1
Penguin 3.3.9
Pika 1.8.23
Donor 2.2.4 (not in use with this config)
Kekka 1.6.9 (not in use with this config)

### Operating System

Win 10

### Anything else?

Sometimes it work, but sometimes it doesnt work until the next bot restart so our rates go down a lot because of this!

**Comment by mateuzplays** [comment]
https://github.com/darkbot-reloaded/DarkBot/assets/173745088/c776b622-d795-4b15-8ff0-90043c192a58

**Comment by Pablete1234** [comment]
Report this to the plugin author, this isn't an issue on the bot's side
