### ISSUE TITLE
Group Members doesn't update after disbanding or getting kicked

### ISSUE THREAD

**Issue by ODAKAB** [darkbot-reloaded/DarkBot#38]
Getting kicked from a group or kicking the last member makes bot think last state of group member list is still our groupmates.
It should update again if there are no group members if that was the issue.

**Comment by ODAKAB** [comment]
Solved in https://github.com/darkbot-reloaded/DarkBot/pull/39

**Comment by Pablete1234** [comment]
Fixed in cb355a1
